## 
## Travis 
language: cpp

compiler:
  - gcc

# Setup repos etc before installation
before_install:
  - sudo apt-get update -qq

# Install dependencies
install:
  # install biicode:

  - wget http://www.biicode.com/downloads/latest/ubuntu32 
  - (! sudo dpkg -i bii-ubuntu32*.deb ) && sudo apt-get -f install
  - rm bii-ubuntu32*.deb
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.1-Linux-i386.tar.gz
  - tar -xzf cmake-3.0.1-Linux-i386.tar.gz
  - sudo cp -fR cmake-3.0.1-Linux-i386/* /usr
  - rm -rf cmake-3.0.1-Linux-i386
  - rm cmake-3.0.1-Linux-i386.tar.gz




# command to run tests
script:
  - cmake --version
  - bii init 
  - bii new lasote/test_game
  - mv *.* blocks/lasote/test_game
  - bii find
  - bii cpp:build  
  - ./bin/lasote_test_game_test
